### ISSUE TITLE
Example doesn't import to Google Authenticator

### ISSUE THREAD

**Issue by niknah** [dim13/otpauth#13] opened 2021-04-15 04:11 UTC
The example in the README doesn't import into google authenticator...
otpauth-migration://offline?data=CjEKCkhlbGxvId6tvu8SGEV4YW1wbGU6YWxpY2VAZ29vZ2xlLmNvbRoHRXhhbXBsZTAC

**Comment by dim13** [comment] 2021-04-15 05:57
Cannot reproduce. Works just fine for me (GA v5.10). Please try again with example QR in README.

**Comment by niknah** [comment] 2021-04-15 06:46
The QRCode works, it's a otpauth://

This one didn't...
otpauth-migration://offline?data=CjEKCkhlbGxvId6tvu8SGEV4YW1wbGU6YWxpY2VAZ29vZ2xlLmNvbRoHRXhhbXBsZTAC

Image...
https://ibb.co/9rt5PKp

**Comment by dim13** [comment] 2021-04-15 09:57
To import `otpauth-migration` links you have to navigate to ⋮ → Transfer accounts → Import accounts and scan it from there.

**Comment by dim13** [comment] 2021-04-15 16:57
Closing as not related to this app.

**Closed by dim13** 2021-04-15 16:57 UTC
